# k8s-apps/cert-manager/selfsigned-issuer.yaml

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {} # Dit is de simplest type: zichzelf ondertekenend