# argocd/applications/01-cert-manager-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-install
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io # Externe Helm Repo
    targetRevision: v1.19.1
    chart: cert-manager
    helm:
      values: |
        installCRDs: true # Cruciaal: Installeer de Custom Resource Definitions
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true